# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3050f2f2fb22338d8379f48fc051aabc18a296d42986873027ad8b73399ea0984c5853082d85da6de84ccc8e0dce767f5b1c73b627c50e9a92bc3cfb4c7c50e5

test:
  secret_key_base: 2fb26a3f9a5c70607afd41b74a3e66fb0b80f750b25ae3529728f4ddb574e122dc8d794f169c7aa5c81f4cd21cb9c154370b621eb5771a9a1272f2cf56c68025

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
